version: '2'

services:
  server:
    build: ./hello-scala/target/docker/stage
    container_name: server
    ports: ["9090:9090"]

  numbers:
    build: ./svc-numbers
    container_name: numbers
    ports: ["9091:9091"]

  graphql:
    build: ./graphql
    container_name: graphql
    ports: ["3000:3000"]
    depends_on:
      - linkerd

  linkerd:
    image: buoyantio/linkerd:0.8.2
    container_name: linkerd
    ports: ["8080:8080", "8081:8081", "9990:9990"]
    volumes: ["./config:/config:ro"]
    command: /config/linkerd.yaml

  namerd:
    image: buoyantio/namerd:0.8.2
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/config:ro"]
    command: /config/namerd.yaml
