version: '2'

services:
  graphql:
    build: graphql/
    container_name: graphql
    ports: ["3000:3000"]

  server:
    build: hello/
    container_name: server
    ports: ["8081:8081"]

  linkerd:
    image: buoyantio/linkerd:0.8.2
    container_name: linkerd
    ports: ["4140:4140", "9990:9990"]
    volumes: ["./config:/config:ro"]
    command: /config/linkerd.yaml

  namerd:
    image: buoyantio/namerd:0.8.2
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/config:ro"]
    command: /config/namerd.yaml
