admin:
  port: 9991

namers: []
storage:
  kind: io.l5d.inMemory
  namespaces:
    default: |
      /host       => /$/inet/web/8080;
      /http/1.1/* => /host;
      /thrift/hi  => /$/inet/server/9090;
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
